/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

import Data.DBAccess;
import Entity.User;
import PLayFair.PlayfairCipher;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bigbo
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public frmMain() {
        initComponents();
        String decryptuser = PlayfairCipher.decrypt(frmLogin.name, "hello");
        decryptuser = decryptuser.substring(0, decryptuser.length() - 1);
        jMenuUser.setText("User: " + decryptuser);
        if("2".equals(frmLogin.role)){
            menuUser.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuUser = new javax.swing.JMenuItem();
        menuTeacher = new javax.swing.JMenuItem();
        menuStudent = new javax.swing.JMenuItem();
        menuSub = new javax.swing.JMenuItem();
        menuTranscript = new javax.swing.JMenuItem();
        jMenuUser = new javax.swing.JMenu();
        jMenuLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(810, 627));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nen2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu1.setText("Manager");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuUser.setText("User");
        menuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserActionPerformed(evt);
            }
        });
        jMenu1.add(menuUser);

        menuTeacher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuTeacher.setText("Teacher");
        menuTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTeacherActionPerformed(evt);
            }
        });
        jMenu1.add(menuTeacher);

        menuStudent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuStudent.setText("Student");
        menuStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStudentActionPerformed(evt);
            }
        });
        jMenu1.add(menuStudent);

        menuSub.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuSub.setText("Subject");
        menuSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSubActionPerformed(evt);
            }
        });
        jMenu1.add(menuSub);

        menuTranscript.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuTranscript.setText("Trancsript");
        menuTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTranscriptActionPerformed(evt);
            }
        });
        jMenu1.add(menuTranscript);

        jMenuBar1.add(jMenu1);

        jMenuUser.setText("User");
        jMenuUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuLogout.setText("Log out");
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuLogout);

        jMenuBar1.add(jMenuUser);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmUser frm = new frmUser();
        frm.setVisible(true);
    }//GEN-LAST:event_menuUserActionPerformed

    private void menuTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTeacherActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmTeacher frm = new frmTeacher();
        frm.setVisible(true);
    }//GEN-LAST:event_menuTeacherActionPerformed

    private void menuStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStudentActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmStudent frm = new frmStudent();
        frm.setVisible(true);
    }//GEN-LAST:event_menuStudentActionPerformed

    private void menuSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSubActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmSubject frm = new frmSubject();
        frm.setVisible(true);
    }//GEN-LAST:event_menuSubActionPerformed

    private void menuTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTranscriptActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmTranscript frm = new frmTranscript();
        frm.setVisible(true);
    }//GEN-LAST:event_menuTranscriptActionPerformed

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        // TODO add your handling code here:
        int out = JOptionPane.showConfirmDialog(null, "Do you want to log out?", "Log out?", JOptionPane.OK_CANCEL_OPTION);
        if (out == 0) {
            frmLogin frm = new frmLogin();
            this.dispose();
            frm.setVisible(true);
        }
    }//GEN-LAST:event_jMenuLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuLogout;
    private javax.swing.JMenu jMenuUser;
    private javax.swing.JMenuItem menuStudent;
    private javax.swing.JMenuItem menuSub;
    private javax.swing.JMenuItem menuTeacher;
    private javax.swing.JMenuItem menuTranscript;
    private javax.swing.JMenuItem menuUser;
    // End of variables declaration//GEN-END:variables
}
